using JS.AMSWeb.Services.Azure;

namespace JS.AMSWeb.Utils
{
    public static class ImageHelper
    {
        //public const string ImageContainerUrl = "https://images.weserv.nl/?url=https://storage.Wowlistix.com.my/";
        //public const string RawImageContainerUrl = "http://storage.Wowlistix.com.my/";

        //public const string ImageContainerUrl = AzureBlobService.AZURE_STORAGE_DOMAIN + AzureBlobService.IMAGE_CONTAINER;
        //public const string RawImageContainerUrl = AzureBlobService.AZURE_STORAGE_DOMAIN + AzureBlobService.IMAGE_CONTAINER;

        public static async Task<string> GetTempUploadedFilePath(IFormFile formFile)
        {
            // Uses Path.GetTempFileName to return a full path for a file, including the file name.
            var filePath = Path.GetTempFileName();

            using (var stream = File.Create(filePath))
            {
                // The formFile is the method parameter which type is IFormFile
                // Saves the files to the local file system using a file name generated by the app.
                await formFile.CopyToAsync(stream);
            }

            return filePath;
        }

        public static string DefaultAvatarUrl()
        {
            return "/img/avatars/sample_avatar.png";
        }
    }
}
